name: Test

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      - name: Checkout
        uses: actions/checkout@v4.1.5
      
      - name: Load cached dependencies
        uses: actions/cache@v4.2.3
        with:
            path: ~/.nuget/packages
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            restore-keys: ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore --locked-mode
        
      - name: Test others
        run: dotnet test -c Release
        